// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Screenplay.Generation.DotNet.for_DotNetAdapterRunner;

public class when_admitting_contributions_with_source_ranges : given.a_runner_context
{
    AdapterRunSnapshot _snapshot = null!;
    AdapterRunRecord _identityLess = null!;

    void Because()
    {
        var validProject = MappedProject(
            "project-valid",
            "Valid.Project",
            "Valid",
            "/checkout/valid/Code.cs",
            "public class Valid { }\n");
        var generatedProject = MappedProject(
            "project-generated",
            "Generated.Project",
            "Generated",
            "/checkout/generated/Generated.g.cs",
            "// <auto-generated/>\npublic class Generated { }\n");
        var unmappedProject = UnmappedProject();
        var validFile = validProject.SourceContext!.Files.Values.Single();
        var generatedFile = generatedProject.SourceContext!.Files.Values.Single();
        var valid = Range(validFile.DisplayPath, validFile.Identity, 1, 1, 1, 7);
        var adapters = new[]
        {
            Adapter("valid", valid),
            Adapter("foreign", valid with { FileIdentity = new SourceFileIdentity { Project = "foreign", Path = validFile.Identity.Path } }),
            Adapter("display-mismatch", valid with { Path = "Other.cs" }),
            Adapter("out-of-bounds", valid with { EndLine = 99 }),
            Adapter("generated", Range(generatedFile.DisplayPath, generatedFile.Identity, 2, 1, 2, 7)),
            Adapter("unmapped", Range("Unmapped.cs", new SourceFileIdentity { Project = "project-unmapped", Path = "Unmapped.cs" }, 1, 1, 1, 7))
        };
        _snapshot = DotNetAdapterRunner.Run(
            adapters.Select(DotNetAdapterRegistration.For),
            new DotNetAnalysisContext([unmappedProject, generatedProject, validProject]),
            Options);

        var strictDescriptor = Descriptor(
            "identity-less",
            language: AdapterSourceLanguage.CSharp,
            hostCapabilities:
            [
                AdapterHostCapability.AuthoredSource,
                AdapterHostCapability.StableSourceLocations,
                AdapterHostCapability.SemanticAnalysis
            ],
            factCapabilities: [GenerationFactCapability.Artifact]);
        var identityLess = new ModernAdapter(strictDescriptor)
        {
            Contribution = ArtifactContribution(strictDescriptor.Identity, valid with { FileIdentity = null })
        };
        _identityLess = DotNetAdapterRunner.Run(
            [DotNetAdapterRegistration.For(identityLess)],
            new DotNetAnalysisContext([validProject]),
            Options).Adapters.Single();
    }

    [Fact] void should_admit_exact_authoritative_source() => Record("valid").Disposition.ShouldEqual(AdapterRunDisposition.Admitted);
    [Fact] void should_reject_foreign_source_identity() => Record("foreign").Disposition.ShouldEqual(AdapterRunDisposition.ContributionRejected);
    [Fact] void should_reject_display_path_mismatch() => Record("display-mismatch").Disposition.ShouldEqual(AdapterRunDisposition.ContributionRejected);
    [Fact] void should_reject_out_of_bounds_coordinates() => Record("out-of-bounds").Disposition.ShouldEqual(AdapterRunDisposition.ContributionRejected);
    [Fact] void should_reject_generated_source() => Record("generated").Disposition.ShouldEqual(AdapterRunDisposition.ContributionRejected);
    [Fact] void should_reject_unmapped_source() => Record("unmapped").Disposition.ShouldEqual(AdapterRunDisposition.ContributionRejected);
    [Fact] void should_reject_identityless_source_for_a_modern_stable_source_adapter() => _identityLess.Disposition.ShouldEqual(AdapterRunDisposition.ContributionRejected);
    [Fact] void should_admit_facts_only_from_the_valid_adapter() => _snapshot.Facts.Select(record => record.Fact.Id.Value).ShouldContainOnly("valid:artifact");

    AdapterRunRecord Record(string id) => _snapshot.Adapters.Single(record => record.Descriptor.Identity.Id == id);

    static ModernAdapter Adapter(string id, SourceRange source)
    {
        var descriptor = Descriptor(id, factCapabilities: [GenerationFactCapability.Artifact]);
        return new ModernAdapter(descriptor) { Contribution = ArtifactContribution(descriptor.Identity, source) };
    }

    static SourceRange Range(
        string path,
        SourceFileIdentity identity,
        int startLine,
        int startColumn,
        int endLine,
        int endColumn) => new()
        {
            Path = path,
            FileIdentity = identity,
            StartLine = startLine,
            StartColumn = startColumn,
            EndLine = endLine,
            EndColumn = endColumn
        };

    static DotNetProjectCompilation UnmappedProject()
    {
        var tree = CSharpSyntaxTree.ParseText("public class Unmapped { }\n", path: "/checkout/unmapped/Unmapped.cs");
        var compilation = CSharpCompilation.Create("Unmapped", [tree], CompilationFrom().References);
        var sourceContext = DotNetSourcePaths.Create(
            "project-unmapped",
            new DotNetSourcePathPolicy
            {
                DisplayRoot = DotNetSourceDisplayRoot.Project,
                CasePolicy = DotNetSourcePathCasePolicy.Ordinal
            },
            []);
        return new DotNetProjectCompilation
        {
            Name = "Unmapped.Project",
            Compilation = compilation,
            SourceContext = sourceContext,
            AuthoredSyntaxTrees = new HashSet<SyntaxTree> { tree }
        };
    }
}
