// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Cratis.Screenplay.Generation.DotNet;

/// <summary>
/// Recognizes compiler- and tool-generated C# source.
/// </summary>
public static class DotNetGeneratedSource
{
    static readonly string[] _generatedSuffixes = [".g.cs", ".g.i.cs", ".generated.cs"];

    /// <summary>
    /// Gets whether a syntax tree represents generated source rather than an authored declaration.
    /// </summary>
    /// <param name="tree">The syntax tree to inspect.</param>
    /// <returns><see langword="true"/> when the tree is generated; otherwise, <see langword="false"/>.</returns>
    public static bool IsGenerated(SyntaxTree tree)
    {
        var path = tree.FilePath.Replace('\\', '/');
        if (path.Split('/', StringSplitOptions.RemoveEmptyEntries).Any(_ =>
                string.Equals(_, "obj", StringComparison.Ordinal) || string.Equals(_, "bin", StringComparison.Ordinal)))
        {
            return true;
        }

        if (_generatedSuffixes.Any(suffix => path.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)))
        {
            return true;
        }

        var text = tree.GetText();
        var linesToRead = Math.Min(text.Lines.Count, 5);
        for (var line = 0; line < linesToRead; line++)
        {
            var value = text.Lines[line].ToString();
            if (value.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase) ||
                value.Contains("@generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}

/// <summary>
/// Converts .NET source paths and Roslyn locations into portable generation provenance.
/// </summary>
public static class DotNetSource
{
    /// <summary>
    /// Gets authored declarations of a symbol in deterministic source order.
    /// </summary>
    /// <param name="symbol">The symbol whose declarations should be inspected.</param>
    /// <returns>The authored declaration references.</returns>
    public static IReadOnlyList<SyntaxReference> AuthoredDeclarationsOf(ISymbol symbol) =>
        AuthoredDeclarationsOf(symbol, tree => !DotNetGeneratedSource.IsGenerated(tree));

    /// <summary>
    /// Gets declarations of a symbol that belong to the authoritative authored-tree set.
    /// </summary>
    /// <param name="symbol">The symbol whose declarations should be inspected.</param>
    /// <param name="authoredSyntaxTrees">The syntax trees established as authored by the workspace host.</param>
    /// <returns>The authored declaration references.</returns>
    public static IReadOnlyList<SyntaxReference> AuthoredDeclarationsOf(
        ISymbol symbol,
        IReadOnlySet<SyntaxTree> authoredSyntaxTrees) =>
        AuthoredDeclarationsOf(symbol, authoredSyntaxTrees.Contains);

    /// <summary>
    /// Gets whether a symbol has at least one authored declaration.
    /// </summary>
    /// <param name="symbol">The symbol to inspect.</param>
    /// <returns><see langword="true"/> when an authored declaration exists; otherwise, <see langword="false"/>.</returns>
    public static bool HasAuthoredDeclaration(ISymbol symbol) => AuthoredDeclarationsOf(symbol).Count > 0;

    /// <summary>
    /// Gets whether a symbol has a declaration in the authoritative authored-tree set.
    /// </summary>
    /// <param name="symbol">The symbol to inspect.</param>
    /// <param name="authoredSyntaxTrees">The syntax trees established as authored by the workspace host.</param>
    /// <returns><see langword="true"/> when an authored declaration exists; otherwise, <see langword="false"/>.</returns>
    public static bool HasAuthoredDeclaration(ISymbol symbol, IReadOnlySet<SyntaxTree> authoredSyntaxTrees) =>
        AuthoredDeclarationsOf(symbol, authoredSyntaxTrees).Count > 0;

    /// <summary>
    /// Gets whether a named type has an authored partial declaration.
    /// </summary>
    /// <param name="type">The named type to inspect.</param>
    /// <returns><see langword="true"/> when an authored declaration is partial; otherwise, <see langword="false"/>.</returns>
    public static bool HasAuthoredPartialDeclaration(INamedTypeSymbol type) =>
        HasPartialDeclaration(AuthoredDeclarationsOf(type));

    /// <summary>
    /// Gets whether a named type has a partial declaration in the authoritative authored-tree set.
    /// </summary>
    /// <param name="type">The named type to inspect.</param>
    /// <param name="authoredSyntaxTrees">The syntax trees established as authored by the workspace host.</param>
    /// <returns><see langword="true"/> when an authored partial declaration exists; otherwise, <see langword="false"/>.</returns>
    public static bool HasAuthoredPartialDeclaration(
        INamedTypeSymbol type,
        IReadOnlySet<SyntaxTree> authoredSyntaxTrees) =>
        HasPartialDeclaration(AuthoredDeclarationsOf(type, authoredSyntaxTrees));

    /// <summary>
    /// Gets attributes whose applications occur in authored source, in deterministic source order.
    /// </summary>
    /// <param name="symbol">The attributed symbol.</param>
    /// <returns>The authored attribute data.</returns>
    public static IReadOnlyList<AttributeData> AuthoredAttributesOf(ISymbol symbol) =>
        AuthoredAttributesOf(symbol, tree => !DotNetGeneratedSource.IsGenerated(tree));

    /// <summary>
    /// Gets attributes whose applications belong to the authoritative authored-tree set.
    /// </summary>
    /// <param name="symbol">The attributed symbol.</param>
    /// <param name="authoredSyntaxTrees">The syntax trees established as authored by the workspace host.</param>
    /// <returns>The authored attribute data.</returns>
    public static IReadOnlyList<AttributeData> AuthoredAttributesOf(
        ISymbol symbol,
        IReadOnlySet<SyntaxTree> authoredSyntaxTrees) =>
        AuthoredAttributesOf(symbol, authoredSyntaxTrees.Contains);

    /// <summary>
    /// Gets every invocation in the host-authoritative authored source, in stable source order.
    /// </summary>
    /// <param name="project">The project compilation and authoritative authored-tree set.</param>
    /// <returns>The authored invocations.</returns>
    /// <exception cref="DotNetAuthoredSyntaxTreeNotInCompilation">An authoritative tree is absent from the compilation.</exception>
    /// <exception cref="DotNetSourceTreeNotMapped">An authoritative tree is absent from the explicit source context.</exception>
    /// <exception cref="DotNetAuthoredSyntaxTreeIdentityNotUnique">Legacy authored trees have missing or duplicate paths.</exception>
    public static IReadOnlyList<InvocationExpressionSyntax> AuthoredInvocationsIn(DotNetProjectCompilation project) =>
        AuthoredNodesIn<InvocationExpressionSyntax>(project);

    /// <summary>
    /// Gets every invocation beneath an authored source scope, in syntax order.
    /// </summary>
    /// <param name="scope">The source scope to inspect.</param>
    /// <param name="project">The project compilation and authoritative authored-tree set.</param>
    /// <returns>The authored invocations, or an empty list when the scope is not authoritative authored source.</returns>
    /// <exception cref="DotNetAuthoredSyntaxTreeNotInCompilation">An authoritative tree is absent from the compilation.</exception>
    /// <exception cref="DotNetSourceTreeNotMapped">An authoritative tree is absent from the explicit source context.</exception>
    public static IReadOnlyList<InvocationExpressionSyntax> AuthoredInvocationsIn(
        SyntaxNode scope,
        DotNetProjectCompilation project) =>
        AuthoredNodesIn<InvocationExpressionSyntax>(scope, project);

    /// <summary>
    /// Gets every assignment in the host-authoritative authored source, in stable source order.
    /// </summary>
    /// <param name="project">The project compilation and authoritative authored-tree set.</param>
    /// <returns>The authored assignments.</returns>
    /// <exception cref="DotNetAuthoredSyntaxTreeNotInCompilation">An authoritative tree is absent from the compilation.</exception>
    /// <exception cref="DotNetSourceTreeNotMapped">An authoritative tree is absent from the explicit source context.</exception>
    /// <exception cref="DotNetAuthoredSyntaxTreeIdentityNotUnique">Legacy authored trees have missing or duplicate paths.</exception>
    public static IReadOnlyList<AssignmentExpressionSyntax> AuthoredAssignmentsIn(DotNetProjectCompilation project) =>
        AuthoredNodesIn<AssignmentExpressionSyntax>(project);

    /// <summary>
    /// Gets every assignment beneath an authored source scope, in syntax order.
    /// </summary>
    /// <param name="scope">The source scope to inspect.</param>
    /// <param name="project">The project compilation and authoritative authored-tree set.</param>
    /// <returns>The authored assignments, or an empty list when the scope is not authoritative authored source.</returns>
    /// <exception cref="DotNetAuthoredSyntaxTreeNotInCompilation">An authoritative tree is absent from the compilation.</exception>
    /// <exception cref="DotNetSourceTreeNotMapped">An authoritative tree is absent from the explicit source context.</exception>
    public static IReadOnlyList<AssignmentExpressionSyntax> AuthoredAssignmentsIn(
        SyntaxNode scope,
        DotNetProjectCompilation project) =>
        AuthoredNodesIn<AssignmentExpressionSyntax>(scope, project);

    /// <summary>
    /// Gets a portable source range for a Roslyn location.
    /// </summary>
    /// <param name="location">The source location.</param>
    /// <param name="sourceRoot">The workspace root used to make the path relative.</param>
    /// <returns>The portable source range, or <see langword="null"/> when the location is not in source.</returns>
    public static SourceRange? Range(Location location, string? sourceRoot)
    {
        if (!location.IsInSource || location.SourceTree is null)
        {
            return null;
        }

        var span = location.GetLineSpan();
        return new()
        {
            Path = RelativePath(span.Path, sourceRoot),
            StartLine = span.StartLinePosition.Line + 1,
            StartColumn = span.StartLinePosition.Character + 1,
            EndLine = span.EndLinePosition.Line + 1,
            EndColumn = span.EndLinePosition.Character + 1
        };
    }

    /// <summary>
    /// Gets a portable source range using the host's authoritative source-file mapping.
    /// </summary>
    /// <param name="location">The source location.</param>
    /// <param name="project">The owning project compilation.</param>
    /// <returns>The mapped source range, or <see langword="null"/> when the location is not authored source.</returns>
    /// <exception cref="DotNetSourceTreeNotMapped">The authored tree is missing from the explicit source context.</exception>
    public static SourceRange? RangeForProject(Location location, DotNetProjectCompilation project)
    {
        if (!location.IsInSource ||
            location.SourceTree is null ||
            !project.AuthoredSyntaxTrees.Contains(location.SourceTree))
        {
            return null;
        }

        if (project.SourceContext is null)
        {
            return Range(location, project.SourceRoot);
        }

        if (!project.SourceContext.Files.TryGetValue(location.SourceTree, out var sourceFile))
        {
            throw new DotNetSourceTreeNotMapped(location.SourceTree.FilePath);
        }

        var span = location.GetLineSpan();
        return new()
        {
            Path = sourceFile.DisplayPath,
            FileIdentity = sourceFile.Identity,
            StartLine = span.StartLinePosition.Line + 1,
            StartColumn = span.StartLinePosition.Character + 1,
            EndLine = span.EndLinePosition.Line + 1,
            EndColumn = span.EndLinePosition.Character + 1
        };
    }

    /// <summary>
    /// Gets deterministic evidence for a symbol's first authored declaration.
    /// </summary>
    /// <param name="symbol">The source symbol.</param>
    /// <param name="adapter">The adapter producing the evidence.</param>
    /// <param name="strength">The evidence strength.</param>
    /// <param name="sourceRoot">The workspace root used to make paths relative.</param>
    /// <param name="explanation">An optional explanation of the evidence.</param>
    /// <returns>The evidence.</returns>
    public static Evidence EvidenceFor(
        ISymbol symbol,
        AdapterIdentity adapter,
        EvidenceStrength strength,
        string? sourceRoot,
        string? explanation = null)
    {
        var location = AuthoredDeclarationsOf(symbol)
            .Select(_ => _.GetSyntax().GetLocation())
            .FirstOrDefault();

        return EvidenceFor(location, adapter, strength, sourceRoot, explanation);
    }

    /// <summary>
    /// Gets deterministic evidence for a symbol's first authoritative authored declaration.
    /// </summary>
    /// <param name="symbol">The source symbol.</param>
    /// <param name="adapter">The adapter producing the evidence.</param>
    /// <param name="project">The owning project compilation and source-path context.</param>
    /// <param name="strength">The evidence strength.</param>
    /// <param name="explanation">An optional explanation of the evidence.</param>
    /// <returns>The evidence.</returns>
    public static Evidence EvidenceFor(
        ISymbol symbol,
        AdapterIdentity adapter,
        DotNetProjectCompilation project,
        EvidenceStrength strength,
        string? explanation = null)
    {
        var location = AuthoredDeclarationsOf(symbol, project.AuthoredSyntaxTrees)
            .Select(_ => _.GetSyntax().GetLocation())
            .FirstOrDefault();

        return EvidenceFor(location, adapter, project, strength, explanation);
    }

    /// <summary>
    /// Gets deterministic evidence anchored at an authored attribute application.
    /// </summary>
    /// <param name="attribute">The authored attribute data.</param>
    /// <param name="adapter">The adapter producing the evidence.</param>
    /// <param name="strength">The evidence strength.</param>
    /// <param name="sourceRoot">The workspace root used to make paths relative.</param>
    /// <param name="explanation">An optional explanation of the evidence.</param>
    /// <returns>The evidence.</returns>
    public static Evidence EvidenceFor(
        AttributeData attribute,
        AdapterIdentity adapter,
        EvidenceStrength strength,
        string? sourceRoot,
        string? explanation = null) =>
        EvidenceFor(
            attribute,
            tree => !DotNetGeneratedSource.IsGenerated(tree),
            adapter,
            strength,
            sourceRoot,
            explanation);

    /// <summary>
    /// Gets deterministic evidence anchored at an attribute application in the authoritative authored-tree set.
    /// </summary>
    /// <param name="attribute">The authored attribute data.</param>
    /// <param name="authoredSyntaxTrees">The syntax trees established as authored by the workspace host.</param>
    /// <param name="adapter">The adapter producing the evidence.</param>
    /// <param name="strength">The evidence strength.</param>
    /// <param name="sourceRoot">The workspace root used to make paths relative.</param>
    /// <param name="explanation">An optional explanation of the evidence.</param>
    /// <returns>The evidence.</returns>
    public static Evidence EvidenceFor(
        AttributeData attribute,
        IReadOnlySet<SyntaxTree> authoredSyntaxTrees,
        AdapterIdentity adapter,
        EvidenceStrength strength,
        string? sourceRoot,
        string? explanation = null) =>
        EvidenceFor(attribute, authoredSyntaxTrees.Contains, adapter, strength, sourceRoot, explanation);

    /// <summary>
    /// Gets deterministic evidence anchored at an attribute application in the authoritative project source.
    /// </summary>
    /// <param name="attribute">The authored attribute data.</param>
    /// <param name="adapter">The adapter producing the evidence.</param>
    /// <param name="project">The owning project compilation and source-path context.</param>
    /// <param name="strength">The evidence strength.</param>
    /// <param name="explanation">An optional explanation of the evidence.</param>
    /// <returns>The evidence.</returns>
    public static Evidence EvidenceFor(
        AttributeData attribute,
        AdapterIdentity adapter,
        DotNetProjectCompilation project,
        EvidenceStrength strength,
        string? explanation = null)
    {
        var reference = attribute.ApplicationSyntaxReference;
        var location = reference is not null && project.AuthoredSyntaxTrees.Contains(reference.SyntaxTree)
            ? reference.GetSyntax().GetLocation()
            : null;

        return EvidenceFor(location, adapter, project, strength, explanation);
    }

    static IReadOnlyList<TNode> AuthoredNodesIn<TNode>(DotNetProjectCompilation project)
        where TNode : SyntaxNode =>
    [
        .. AuthoredTreesIn(project)
            .SelectMany(tree => tree.GetRoot().DescendantNodesAndSelf().OfType<TNode>().OrderBy(node => node.SpanStart))
    ];

    static IReadOnlyList<TNode> AuthoredNodesIn<TNode>(SyntaxNode scope, DotNetProjectCompilation project)
        where TNode : SyntaxNode
    {
        ValidateScopedAuthoredTrees(project);
        return project.AuthoredSyntaxTrees.Contains(scope.SyntaxTree)
            ? [.. scope.DescendantNodesAndSelf().OfType<TNode>().OrderBy(node => node.SpanStart)]
            : [];
    }

    static void ValidateScopedAuthoredTrees(DotNetProjectCompilation project)
    {
        var compilationTrees = project.Compilation.SyntaxTrees.ToHashSet();
        foreach (var tree in project.AuthoredSyntaxTrees)
        {
            if (!compilationTrees.Contains(tree))
            {
                throw new DotNetAuthoredSyntaxTreeNotInCompilation(tree.FilePath);
            }

            if (project.SourceContext?.Files.ContainsKey(tree) == false)
            {
                throw new DotNetSourceTreeNotMapped(tree.FilePath);
            }
        }
    }

    static IReadOnlyList<SyntaxTree> AuthoredTreesIn(DotNetProjectCompilation project)
    {
        var compilationTrees = project.Compilation.SyntaxTrees.ToHashSet();
        foreach (var tree in project.AuthoredSyntaxTrees)
        {
            if (!compilationTrees.Contains(tree))
            {
                throw new DotNetAuthoredSyntaxTreeNotInCompilation(tree.FilePath);
            }
        }

        if (project.SourceContext is null)
        {
            var paths = project.AuthoredSyntaxTrees.Select(tree => tree.FilePath.Replace('\\', '/')).ToArray();
            if (paths.Any(string.IsNullOrWhiteSpace) || paths.Distinct(StringComparer.Ordinal).Count() != paths.Length)
            {
                throw new DotNetAuthoredSyntaxTreeIdentityNotUnique();
            }

            return
            [
                .. project.AuthoredSyntaxTrees.OrderBy(tree => tree.FilePath, StringComparer.Ordinal)
            ];
        }

        foreach (var tree in project.AuthoredSyntaxTrees)
        {
            if (!project.SourceContext.Files.ContainsKey(tree))
            {
                throw new DotNetSourceTreeNotMapped(tree.FilePath);
            }
        }

        return
        [
            .. project.AuthoredSyntaxTrees
                .OrderBy(tree => project.SourceContext.Files[tree].Identity.Project, StringComparer.Ordinal)
                .ThenBy(tree => project.SourceContext.Files[tree].Identity.Path, StringComparer.Ordinal)
        ];
    }

    static IReadOnlyList<SyntaxReference> AuthoredDeclarationsOf(
        ISymbol symbol,
        Func<SyntaxTree, bool> isAuthored) =>
    [
        .. symbol.DeclaringSyntaxReferences
            .Where(_ => isAuthored(_.SyntaxTree))
            .OrderBy(_ => _.SyntaxTree.FilePath, StringComparer.Ordinal)
            .ThenBy(_ => _.Span.Start)
    ];

    static bool HasPartialDeclaration(IEnumerable<SyntaxReference> declarations) =>
        declarations
            .Select(_ => _.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(_ => _.Modifiers.Any(SyntaxKind.PartialKeyword));

    static IReadOnlyList<AttributeData> AuthoredAttributesOf(
        ISymbol symbol,
        Func<SyntaxTree, bool> isAuthored) =>
    [
        .. symbol.GetAttributes()
            .Where(_ => _.ApplicationSyntaxReference is not null && isAuthored(_.ApplicationSyntaxReference.SyntaxTree))
            .OrderBy(_ => _.ApplicationSyntaxReference!.SyntaxTree.FilePath, StringComparer.Ordinal)
            .ThenBy(_ => _.ApplicationSyntaxReference!.Span.Start)
    ];

    static Evidence EvidenceFor(
        AttributeData attribute,
        Func<SyntaxTree, bool> isAuthored,
        AdapterIdentity adapter,
        EvidenceStrength strength,
        string? sourceRoot,
        string? explanation)
    {
        var reference = attribute.ApplicationSyntaxReference;
        var location = reference is not null && isAuthored(reference.SyntaxTree)
            ? reference.GetSyntax().GetLocation()
            : null;

        return EvidenceFor(location, adapter, strength, sourceRoot, explanation);
    }

    static Evidence EvidenceFor(
        Location? location,
        AdapterIdentity adapter,
        EvidenceStrength strength,
        string? sourceRoot,
        string? explanation) => new()
        {
            Adapter = adapter,
            Strength = strength,
            Source = location is null ? null : Range(location, sourceRoot),
            Explanation = explanation
        };

    static Evidence EvidenceFor(
        Location? location,
        AdapterIdentity adapter,
        DotNetProjectCompilation project,
        EvidenceStrength strength,
        string? explanation) => new()
        {
            Adapter = adapter,
            Strength = strength,
            Source = location is null ? null : RangeForProject(location, project),
            Explanation = explanation
        };

    static string RelativePath(string path, string? sourceRoot)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            return string.Empty;
        }

        if (string.IsNullOrWhiteSpace(sourceRoot) || !Path.IsPathFullyQualified(path))
        {
            return path.Replace('\\', '/');
        }

        var relative = Path.GetRelativePath(sourceRoot, path).Replace('\\', '/');
        return relative == ".." || relative.StartsWith("../", StringComparison.Ordinal)
            ? Path.GetFileName(path)
            : relative;
    }
}
