// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.CodeAnalysis;

namespace Cratis.Screenplay.Generation.DotNet;

/// <summary>
/// Recognizes compiler- and tool-generated C# source.
/// </summary>
public static class DotNetGeneratedSource
{
    static readonly string[] _generatedSuffixes = [".g.cs", ".g.i.cs", ".generated.cs"];

    /// <summary>
    /// Gets whether a syntax tree represents generated source rather than an authored declaration.
    /// </summary>
    /// <param name="tree">The syntax tree to inspect.</param>
    /// <returns><see langword="true"/> when the tree is generated; otherwise, <see langword="false"/>.</returns>
    public static bool IsGenerated(SyntaxTree tree)
    {
        var path = tree.FilePath.Replace('\\', '/');
        if (path.Split('/', StringSplitOptions.RemoveEmptyEntries).Any(_ =>
                string.Equals(_, "obj", StringComparison.Ordinal) || string.Equals(_, "bin", StringComparison.Ordinal)))
        {
            return true;
        }

        if (_generatedSuffixes.Any(suffix => path.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)))
        {
            return true;
        }

        var text = tree.GetText();
        var linesToRead = Math.Min(text.Lines.Count, 5);
        for (var line = 0; line < linesToRead; line++)
        {
            var value = text.Lines[line].ToString();
            if (value.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase) ||
                value.Contains("@generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}

/// <summary>
/// Converts .NET source paths and Roslyn locations into portable generation provenance.
/// </summary>
public static class DotNetSource
{
    /// <summary>
    /// Gets a portable source range for a Roslyn location.
    /// </summary>
    /// <param name="location">The source location.</param>
    /// <param name="sourceRoot">The workspace root used to make the path relative.</param>
    /// <returns>The portable source range, or <c>null</c> when the location is not in source.</returns>
    public static SourceRange? Range(Location location, string? sourceRoot)
    {
        if (!location.IsInSource || location.SourceTree is null)
        {
            return null;
        }

        var span = location.GetLineSpan();
        return new()
        {
            Path = RelativePath(span.Path, sourceRoot),
            StartLine = span.StartLinePosition.Line + 1,
            StartColumn = span.StartLinePosition.Character + 1,
            EndLine = span.EndLinePosition.Line + 1,
            EndColumn = span.EndLinePosition.Character + 1
        };
    }

    /// <summary>
    /// Gets deterministic evidence for a symbol's first authored declaration.
    /// </summary>
    /// <param name="symbol">The source symbol.</param>
    /// <param name="adapter">The adapter producing the evidence.</param>
    /// <param name="strength">The evidence strength.</param>
    /// <param name="sourceRoot">The workspace root used to make paths relative.</param>
    /// <param name="explanation">An optional explanation of the evidence.</param>
    /// <returns>The evidence.</returns>
    public static Evidence EvidenceFor(
        ISymbol symbol,
        AdapterIdentity adapter,
        EvidenceStrength strength,
        string? sourceRoot,
        string? explanation = null)
    {
        var location = symbol.Locations
            .Where(_ => _.IsInSource && _.SourceTree is not null && !DotNetGeneratedSource.IsGenerated(_.SourceTree))
            .OrderBy(_ => _.SourceTree!.FilePath, StringComparer.Ordinal)
            .ThenBy(_ => _.SourceSpan.Start)
            .FirstOrDefault();

        return new()
        {
            Adapter = adapter,
            Strength = strength,
            Source = location is null ? null : Range(location, sourceRoot),
            Explanation = explanation
        };
    }

    static string RelativePath(string path, string? sourceRoot)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            return string.Empty;
        }

        if (string.IsNullOrWhiteSpace(sourceRoot) || !Path.IsPathFullyQualified(path))
        {
            return path.Replace('\\', '/');
        }

        var relative = Path.GetRelativePath(sourceRoot, path).Replace('\\', '/');
        return relative == ".." || relative.StartsWith("../", StringComparison.Ordinal)
            ? Path.GetFileName(path)
            : relative;
    }
}
