// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Screenplay.Generation.DotNet.for_DotNetGeneratedSource;

public class when_recognizing_generated_source : Specification
{
    bool _objPath;
    bool _generatedSuffix;
    bool _generatedHeader;
    bool _authored;

    void Because()
    {
        _objPath = DotNetGeneratedSource.IsGenerated(CSharpSyntaxTree.ParseText("class Generated;", path: "/workspace/obj/Generated.cs"));
        _generatedSuffix = DotNetGeneratedSource.IsGenerated(CSharpSyntaxTree.ParseText("class Generated;", path: "/workspace/Generated.g.cs"));
        _generatedHeader = DotNetGeneratedSource.IsGenerated(CSharpSyntaxTree.ParseText("// <auto-generated/>\nclass Generated;", path: "/workspace/Generated.cs"));
        _authored = DotNetGeneratedSource.IsGenerated(CSharpSyntaxTree.ParseText("class Authored;", path: "/workspace/Authored.cs"));
    }

    [Fact] void should_recognize_the_obj_path() => _objPath.ShouldBeTrue();
    [Fact] void should_recognize_the_generated_suffix() => _generatedSuffix.ShouldBeTrue();
    [Fact] void should_recognize_the_generated_header() => _generatedHeader.ShouldBeTrue();
    [Fact] void should_not_recognize_authored_source() => _authored.ShouldBeFalse();
}
