<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Cratis.Screenplay.Generation.Specs</AssemblyName>
        <RootNamespace>Cratis.Screenplay.Generation</RootNamespace>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <DedicatedSpecsProject>true</DedicatedSpecsProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Cratis.Specifications" />
        <PackageReference Include="Cratis.Specifications.XUnit" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <ProjectReference Include="../Generation.Contracts/Generation.Contracts.csproj" />
        <ProjectReference Include="../Generation/Generation.csproj" />
    </ItemGroup>
</Project>
